site_name: MkDocs Text Export Plugin
theme:
  name: readthedocs # Using a standard theme for simplicity for now
use_directory_urls: true # More common default
plugins:
  - search
  # If we want to use text-export for its own docs:
  # - text-export:
  #     markdown: true # e.g., generate markdown versions of the docs

nav:
  - Introduction: index.md
  - Configuration Options: options.md
  - Custom Theme Handlers: theme_handlers.md # Will create this page

repo_url: https://github.com/twardoch/mkdocs-text-export-plugin
edit_uri: edit/master/docs/docs/ # edit_uri should point to the 'docs/docs' subdirectory if pages are there

# remote_name is not a standard mkdocs.yml option, removing.