name: Python CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        # Ensure all dependencies for setup.py are met, including html22text from git
        pip install .

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check formatting with black
      run: |
        pip install black
        black --check .

    - name: Static type checking with mypy
      run: |
        pip install mypy types-setuptools types-beautifulsoup4
        mypy . --exclude venv --exclude docs/theme-handler/cinder.py --ignore-missing-imports

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
        # You can optionally upload the artifacts:
        # uses: actions/upload-artifact@v3
        # with:
        #   name: package-${{ matrix.python-version }}
        #   path: dist/
